# -*- coding: utf-8 -*-
"""cnn ResNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqKLUz6LpsyebTRC7WG1z2rc-UVw-hL6
"""

ALEXTNET

"""use a pre trained Resnet50 model to predict what is an image (in case cat or dog"""

from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input,decode_predictions
import numpy as np

model=ResNet50(weights='imagenet')

img_path='/content/cat.jpeg'
img=image.load_img(img_path,target_size=(224,224))
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
x=preprocess_input(x)

preds=model.predict(x)
print("predicted",decode_predictions(preds,top=3)[0])



