# -*- coding: utf-8 -*-
"""Face Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3Qqv_bR_m3YOF7q_2MNYzHlEBJ222pw
"""

import cv2
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt

image=cv2.imread('smile pic.jpg')
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

#face_casecade=cv2.face_CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

#Detect faces
faces=face_cascade.detectMultiScale(gray,scaleFactor=1.1,minNeighbors=5)
#Draw rectangles
for (x,y,w,h) in faces:
  cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,0),2)
#Show image
cv2_imshow(image)
cv2.waitKey(0)
cv2.destroyAllWindows()

import cv2
from google.colab.patches import cv2_imshow

#Load Haar casecade for face ,eyes ,and smile detction

face_cascade=cv2.CascadeClassifier(cv2.data.haarcascades +'haarcasecade_fontalface_deafult.xml')
eye_cascade=cv2.CascadeClassifier(cv2.data.haarcascades +'haarcasecade_eye.xml')
smile_cascade=cv2.CascadeClassifier(cv2.data.haarcascades +'haarcasecade_smile.xml')

#Reaplce 'your_image .jpg' with the actual uload file name
image=cv2.imread('/content/smile pic.jpg')
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

#Detect faces
#faces=face_cascade.detectMultiScale(gray,scaleFactor=1.3,minNeighbors=5)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

for (x,y,w,h)in faces :
  #draw a rectangle around each faces
  cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,0),2)
  roi_gray=gray[y:y+h,x:x+w]
  roi_color=image[y:y+h,x:x+w]
  #Detect eyes inside the faces region

  eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
  eyes=eye_cascade.detectMultiScale(roi_gray,scaleFactor=1.1,minNeighbors=10)

  for (ex,ey,ew,eh) in eyes:
    #draw a rectangle around each eyes
    cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

    #Detect smiles inside the face  region
    smiles=smile_cascade.detectMultiScale(roi_gray,scaleFactor=1.7,minNeighbors=22)
    for (sx,sy,sw,sh) in smiles:
      #draw a rectangle around each smile
     cv2.rectangle(roi_color,(sx,sy),(sx+sw,sy+sh),(0,0,255),2)

cv2_imshow(image)
cv2.waitKey(0)
cv2.destroyAllWindows()

